import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import { createPinia, setActivePinia } from 'pinia'
import { createMemoryHistory, createRouter } from 'vue-router'
import { adminApi, adminAuthApi, onboardingApi, profileApi } from '@/api'
import AdminLoginView from '@/views/AdminLoginView.vue'
import LoginView from '@/views/LoginView.vue'
import OnboardingView from '@/views/OnboardingView.vue'
import ProfileReportView from '@/views/ProfileReportView.vue'
import AdminSettingsView from '@/views/AdminSettingsView.vue'

const fixtures=vi.hoisted(()=>({
  session:{id:'s1',user_id:'u1',step:'objective_profile',status:'active',round_count:0,turn_count:0,row_version:1,min_rounds:6,max_rounds:12,completeness:0,provider_name:'mock',model_name:'m',prompt_version:'v1',prompt_id:null,prompt_hash:'a'.repeat(64),objective_profile:null,dimension_scores:{},profile_evidence:{},skipped_dimensions:[],followup_counts:{},current_dimension:null,current_question:null},
  minorProfile:{profile:{id:'p1',user_id:'u1',session_id:'s1',version:1,objective_profile:{age_range:'minor',gender:'prefer_not_to_say',asset_level:'A1',employment_status:'student',income_range:'I1',debt_pressure:'none',emergency_fund_months:0,investment_experience:'none',fund_horizon:'under_1_year',loss_reaction:'sell_all'},dimension_scores:{risk_capacity:10,liquidity_resilience:20,experience:0},profile_evidence:{},archetype_code:'STEADY_GUARDIAN',archetype_title:'稳健守望者',risk_level:'conservative',loss_tolerance_percent:5,confidence:.5,completeness:.8,education_only:true,report_summary:{traits:['重视安全','愿意学习'],risk_notice:'先学习基础金融知识',reasoning:['资金期限较短'],low_confidence:['investment_goal']}},recommendations:[{id:'r',direction:'cash_fixed_income',score:1,rank:1,reason:'建立基础认知',actionable:false,selected:false}]}
}))

vi.mock('@/api',()=>({
  authApi:{login:vi.fn(),register:vi.fn(),me:vi.fn()},
  adminAuthApi:{login:vi.fn(),me:vi.fn()},
  onboardingApi:{current:vi.fn().mockResolvedValue(fixtures.session),create:vi.fn(),saveObjective:vi.fn(),sendMessage:vi.fn(),skip:vi.fn(),complete:vi.fn()},
  profileApi:{latest:vi.fn().mockResolvedValue(fixtures.minorProfile),select:vi.fn()},
  adminApi:{list:vi.fn().mockResolvedValue([{id:'1',capability:'text',provider:'mock',model_name:'mock-structured-v1',base_url:null,api_key_configured:true,prompt_version:'v1',min_rounds:6,max_rounds:12,enabled:true,version:2}]),update:vi.fn(),test:vi.fn()},
}))

const mountWithPinia=(component:object)=>{const router=createRouter({history:createMemoryHistory(),routes:[{path:'/',component:{template:'<div />'}},{path:'/:pathMatch(.*)*',component:{template:'<div />'}}]});return mount(component,{global:{plugins:[createPinia(),router]}})}
beforeEach(()=>{localStorage.clear();setActivePinia(createPinia());vi.mocked(onboardingApi.current).mockResolvedValue(fixtures.session as never);vi.mocked(profileApi.latest).mockResolvedValue(fixtures.minorProfile as never);vi.mocked(adminApi.list).mockResolvedValue([
  {id:'1',capability:'text',provider:'mock',model_name:'mock-structured-v1',base_url:null,api_key_configured:true,prompt_version:'v1',min_rounds:6,max_rounds:12,enabled:true,version:2},
  {id:'2',capability:'stt',provider:'browser',model_name:'web-speech-recognition',base_url:null,api_key_configured:false,prompt_version:'v1',min_rounds:6,max_rounds:12,enabled:true,version:1},
  {id:'3',capability:'tts',provider:'browser',model_name:'web-speech-synthesis',base_url:null,api_key_configured:false,prompt_version:'v1',min_rounds:6,max_rounds:12,enabled:true,version:1},
])})
afterEach(()=>{delete (globalThis as any).SpeechRecognition;delete (globalThis as any).webkitSpeechRecognition;delete (globalThis as any).speechSynthesis;delete (globalThis as any).SpeechSynthesisUtterance})

describe('full views',()=>{
  it('switches between login and registration',async()=>{const wrapper=mountWithPinia(LoginView);expect(wrapper.text()).toContain('登录');await wrapper.get('[data-test="auth-mode"]').trigger('click');expect(wrapper.text()).toContain('创建账户');expect(wrapper.find('input[name="display-name"]').exists()).toBe(true)})
  it('provides a dedicated admin login without registration',async()=>{vi.mocked(adminAuthApi.login).mockResolvedValue({access_token:'admin-token',token_type:'bearer',user:{id:'a',email:'admin@test.cn',role:'admin',status:'active'}});const wrapper=mountWithPinia(AdminLoginView);expect(wrapper.text()).toContain('管理端登录');expect(wrapper.text()).not.toContain('创建账户');expect(wrapper.find('input[name="password"]').exists()).toBe(true)})
  it('starts the mentor flow and shows the first of ten choice steps',async()=>{const wrapper=mountWithPinia(OnboardingView);await flushPromises();expect(wrapper.text()).toContain('沈砚先生');await wrapper.get('[data-test="start-onboarding"]').trigger('click');expect(wrapper.text()).toContain('1 / 10');expect(wrapper.findAll('[data-test="objective-choice"]').length).toBeGreaterThan(2)})
  it('renders the server-owned question unchanged after restore',async()=>{const serverQuestion='这是由服务端保存的问题，刷新后仍应完全一致。';vi.mocked(onboardingApi.current).mockResolvedValue({...fixtures.session,step:'conversation',completeness:.4,current_dimension:'risk_tolerance',current_question:serverQuestion} as never);const first=mountWithPinia(OnboardingView);await flushPromises();expect(first.text()).toContain(serverQuestion);first.unmount();const second=mountWithPinia(OnboardingView);await flushPromises();expect(second.text()).toContain(serverQuestion)})
  it('hides the question card when the last assistant reply already contains it',async()=>{const question='你更看重本金安全还是收益弹性？';localStorage.setItem('finance-god-messages:u1:s1',JSON.stringify([{role:'user',content:'我想稳一点'},{role:'assistant',content:`我听到了你的谨慎。${question}`}]));vi.mocked(onboardingApi.current).mockResolvedValue({...fixtures.session,step:'conversation',completeness:.4,current_dimension:'risk_tolerance',current_question:question} as never);const wrapper=mountWithPinia(OnboardingView);await flushPromises();expect(wrapper.find('.current-question').exists()).toBe(false);expect(wrapper.text()).toContain(question)})
  it('toggles recognition and speech controls from their real initial states',async()=>{class Recognition{lang='';interimResults=false;continuous=false;onresult=null;onerror=null;onend=null;start=vi.fn();stop=vi.fn()}Object.defineProperty(globalThis,'SpeechRecognition',{value:Recognition,configurable:true});Object.defineProperty(globalThis,'speechSynthesis',{value:{cancel:vi.fn(),speak:vi.fn()},configurable:true});Object.defineProperty(globalThis,'SpeechSynthesisUtterance',{value:class{lang='';constructor(public text:string){}},configurable:true});vi.mocked(onboardingApi.current).mockResolvedValue({...fixtures.session,step:'conversation',current_dimension:'risk_tolerance',current_question:'服务端问题'} as never);const wrapper=mountWithPinia(OnboardingView);await flushPromises();const record=wrapper.get('button[aria-label="开始语音输入"]');await record.trigger('click');expect(wrapper.find('button[aria-label="停止录音"]').exists()).toBe(true);await wrapper.get('button[aria-label="停止录音"]').trigger('click');expect(wrapper.find('button[aria-label="开始语音输入"]').exists()).toBe(true);const speech=wrapper.get('button[aria-label="关闭语音播报"]');await speech.trigger('click');expect(wrapper.find('button[aria-label="开启语音播报"]').exists()).toBe(true)})
  it('shows text fallback when recognition is unavailable',async()=>{vi.mocked(onboardingApi.current).mockResolvedValue({...fixtures.session,step:'conversation',current_dimension:'risk_tolerance',current_question:'服务端问题'} as never);const wrapper=mountWithPinia(OnboardingView);await flushPromises();await wrapper.get('button[aria-label="开始语音输入"]').trigger('click');expect(wrapper.text()).toContain('已切换为文字输入')})
  it('shows a retry action when session restore fails',async()=>{vi.mocked(onboardingApi.current).mockRejectedValue(new Error('服务暂不可用'));const wrapper=mountWithPinia(OnboardingView);await flushPromises();expect(wrapper.get('[role="alert"]').text()).toContain('服务暂不可用');expect(wrapper.get('[data-test="retry-restore"]').text()).toContain('重试')})
  it('renders education-only report without a direction selection button',async()=>{const wrapper=mountWithPinia(ProfileReportView);await flushPromises();expect(wrapper.text()).toContain('稳健守望者');expect(wrapper.text()).toContain('金融教育');expect(wrapper.find('[data-test="select-direction"]').exists()).toBe(false);expect(wrapper.find('details').exists()).toBe(true)})
  it('opens the trading desk after saving a selected direction',async()=>{const adult=structuredClone(fixtures.minorProfile) as any;adult.profile.education_only=false;adult.recommendations=[{id:'r',direction:'cash_fixed_income',score:70,rank:1,reason:'稳健',actionable:true,selected:false}];vi.mocked(profileApi.latest).mockResolvedValue(adult);vi.mocked(profileApi.select).mockResolvedValue(undefined as never);const router=createRouter({history:createMemoryHistory(),routes:[{path:'/desk',component:{template:'<div />'}},{path:'/:pathMatch(.*)*',component:{template:'<div />'}}]});const wrapper=mount(ProfileReportView,{global:{plugins:[createPinia(),router]}});await flushPromises();await wrapper.get('[data-test="select-direction"]').trigger('click');await flushPromises();expect(profileApi.select).toHaveBeenCalledWith('p1','cash_fixed_income');expect(router.currentRoute.value.path).toBe('/desk');expect(router.currentRoute.value.query.direction).toBe('cash_fixed_income')})
  it('uses controlled text provider settings without exposing a secret input',async()=>{const wrapper=mountWithPinia(AdminSettingsView);await flushPromises();expect(wrapper.text()).toContain('已配置');expect(wrapper.text()).not.toContain('sk-');expect(wrapper.findAll('[role="tab"]').length).toBe(3);expect(wrapper.find('select[name="provider"]').exists()).toBe(true);await wrapper.get('select[name="provider"]').setValue('deepseek');expect(wrapper.findAll('select[name="model"] option').map(item=>item.attributes('value'))).toEqual(['deepseek-v4-flash','deepseek-v4-pro']);await wrapper.get('select[name="provider"]').setValue('stepfun');expect(wrapper.findAll('select[name="model"] option').map(item=>item.attributes('value'))).toEqual(['step-3.5-flash-2603']);expect(wrapper.text()).toContain('StepFun 凭据');expect(wrapper.find('input[name="base-url"]').attributes('value')).toBe('https://api.stepfun.com/v1');expect(wrapper.find('input[name="base-url"]').attributes('readonly')).toBeDefined();expect(wrapper.find('input[name="api-key"]').exists()).toBe(false)})
  it('shows mock disclosure and no evidence confirmation panel during conversation',async()=>{vi.mocked(onboardingApi.current).mockResolvedValue({...fixtures.session,step:'conversation',completeness:.4,current_dimension:'risk_tolerance',current_question:'生活化问题',provider_name:'mock'} as never);const wrapper=mountWithPinia(OnboardingView);await flushPromises();expect(wrapper.text()).toContain('模拟 AI');expect(wrapper.find('.evidence-panel').exists()).toBe(false);expect(wrapper.find('textarea[aria-label="回复沈砚"]').exists()).toBe(true)})
  it('does not save an already selected direction again',async()=>{const adult=structuredClone(fixtures.minorProfile) as any;adult.profile.education_only=false;adult.recommendations=[{id:'r',direction:'cash_fixed_income',score:70,rank:1,reason:'稳健',actionable:true,selected:true}];vi.mocked(profileApi.latest).mockResolvedValue(adult);const wrapper=mountWithPinia(ProfileReportView);await flushPromises();const button=wrapper.get('[data-test="select-direction"]');expect(button.attributes('disabled')).toBeDefined();await button.trigger('click');expect(profileApi.select).not.toHaveBeenCalled();expect(wrapper.text()).toContain('70')})
})
