<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';import { CheckCircle2, KeyRound, LoaderCircle, PlugZap, Save } from 'lucide-vue-next';import { adminApi } from '@/api';import { editableSetting, validateSetting } from '@/services/admin';import type { Capability, EditableAISetting } from '@/types/api'
const labels:Record<Capability,string>={text:'文本模型',stt:'语音识别',tts:'语音播报'};const descriptions:Record<Capability,string>={text:'提问、提取与自然语言表达',stt:'将用户语音转为文字',tts:'将导师回复播报为语音'}
const settings=ref<EditableAISetting[]>([]),active=ref<Capability>('text'),loading=ref(true),saving=ref(false),testing=ref(false),message=ref(''),error=ref('');const current=computed(()=>settings.value.find(s=>s.capability===active.value))
onMounted(async()=>{try{settings.value=(await adminApi.list()).map(editableSetting)}catch(e){error.value=e instanceof Error?e.message:'配置加载失败'}finally{loading.value=false}})
async function save(){if(!current.value)return;const invalid=validateSetting(current.value);if(invalid){error.value=invalid;return}saving.value=true;error.value='';message.value='';try{const prompt=current.value.prompt_content,updated=await adminApi.update(current.value);Object.assign(current.value,editableSetting(updated),{prompt_content:prompt});message.value='配置已保存并记录版本'}catch(e){error.value=e instanceof Error?e.message:'保存失败'}finally{saving.value=false}}
async function testConnection(){if(!current.value)return;testing.value=true;error.value='';message.value='';try{const result=await adminApi.test({capability:current.value.capability,provider:current.value.provider,model_name:current.value.model_name});message.value=result.ok?`连接正常 · ${result.adapter}`:'连接未通过'}catch(e){error.value=e instanceof Error?e.message:'连接测试失败'}finally{testing.value=false}}
</script>
<template><main class="admin-page"><header class="app-header"><RouterLink class="wordmark" to="/app/exe"><span>策</span>Finance God</RouterLink><span class="admin-badge">管理员</span></header><section class="admin-head"><p class="chapter">系统设置</p><h1>AI 能力与访谈边界</h1><p>配置变更按版本留痕，服务器密钥不会回传浏览器。</p></section><section v-if="loading" class="center-state">正在读取配置…</section><section v-else class="settings-workspace"><nav class="settings-tabs" role="tablist" aria-label="AI 能力"><button v-for="item in settings" :key="item.capability" role="tab" :aria-selected="active===item.capability" :class="{active:active===item.capability}" @click="active=item.capability"><span>{{ labels[item.capability] }}</span><small>{{ item.enabled?'运行中':'已停用' }}</small></button></nav>
  <form v-if="current" class="settings-form" @submit.prevent="save"><div class="settings-title"><div><p class="chapter">{{ current.capability.toUpperCase() }}</p><h2>{{ labels[current.capability] }}</h2><p>{{ descriptions[current.capability] }}</p></div><label class="switch"><input v-model="current.enabled" type="checkbox"><span aria-hidden="true"></span>{{ current.enabled?'已启用':'已停用' }}</label></div><div class="field-grid"><label>提供商<input v-model.trim="current.provider" required></label><label>模型名称<input v-model.trim="current.model_name" required></label><label class="key-field">环境变量引用<span class="input-with-status"><KeyRound :size="18"/><input v-model.trim="current.api_key_ref" :disabled="current.clear_api_key_ref" autocomplete="off" placeholder="例如 OPENAI_API_KEY"><em>{{ current.api_key_configured?'已配置':'未配置' }}</em></span></label><label v-if="current.api_key_configured" class="clear-key"><input v-model="current.clear_api_key_ref" type="checkbox">清除已配置的密钥引用</label></div><div class="round-settings"><label>最少轮次<input v-model.number="current.min_rounds" type="number" min="6" max="12"></label><span>至</span><label>最多轮次<input v-model.number="current.max_rounds" type="number" min="6" max="12"></label></div><template v-if="current.capability==='text'"><div class="field-grid"><label>Prompt 版本<input v-model.trim="current.prompt_version" required></label></div><label>Prompt 内容<textarea v-model="current.prompt_content" rows="7" placeholder="创建新版本时填写，已有版本保持为空即可"></textarea></label></template><p class="version-note"><CheckCircle2 :size="17"/>当前配置版本 v{{ current.version }}</p><p v-if="error" class="form-error" role="alert">{{ error }}</p><p v-if="message" class="success-note" role="status">{{ message }}</p><div class="form-actions"><button type="button" class="secondary-button" :disabled="testing" @click="testConnection"><LoaderCircle v-if="testing" class="spin" :size="18"/><PlugZap v-else :size="18"/>测试连接</button><button class="primary-button compact" :disabled="saving"><LoaderCircle v-if="saving" class="spin" :size="18"/><Save v-else :size="18"/>保存配置</button></div></form></section></main></template>
