<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft, ArrowRight, Check, LogOut, Mic, MicOff, Send, Sparkles, Volume2, VolumeX } from 'lucide-vue-next'
import { useAuthStore } from '@/stores/auth';import { objectiveSteps, useOnboardingStore } from '@/stores/onboarding';import { createSpeechController } from '@/composables/useSpeech'
import mentorImageUrl from '@/assets/images/investment-mentor.webp'
const store=useOnboardingStore(),auth=useAuthStore(),router=useRouter(),route=useRoute(),started=ref(false),draft=ref(''),inputMode=ref<'text'|'voice'>('text'),thinkingIndex=ref(0),mentorImageFailed=ref(false),messageStream=ref<HTMLElement|null>(null);const speech=createSpeechController(),{listening,transcript,error:speechError,speaking}=speech;const thinking=['正在梳理你的投资线索','正在权衡时间与风险','正在寻找下一位投资大师'];let timer:number|undefined
const phase=computed(()=>{if(!store.session)return store.error?'restore_error':'loading';if(store.session.step==='objective_profile')return started.value?'objective':'welcome';return store.session.step})
const progress=computed(()=>phase.value==='objective'?(store.objectiveIndex+1)/objectiveSteps.length:store.session?.completeness||0)
const sensitive=computed(()=>store.session?.current_dimension==='income_stability')
const currentQuestion=computed(()=>store.session?.current_question||'正在准备下一问…')
const showQuestionCard=computed(()=>{const q=(store.session?.current_question||'').trim();if(!q)return false;const lastAssistant=[...store.messages].reverse().find(m=>m.role==='assistant');return !lastAssistant||!lastAssistant.content.includes(q)})
async function restoreSession(){try{await store.restore();if(store.session?.objective_profile)started.value=true}catch(e){store.error=e instanceof Error?e.message:'无法恢复会话'}}
onMounted(async()=>{await restoreSession();timer=window.setInterval(()=>thinkingIndex.value=(thinkingIndex.value+1)%thinking.length,1800)})
onBeforeUnmount(()=>clearInterval(timer));watch(transcript,(value)=>{if(value){draft.value=value;inputMode.value='voice'}});watch([()=>store.messages.length,currentQuestion],async()=>{await nextTick();if(messageStream.value)messageStream.value.scrollTop=messageStream.value.scrollHeight})
async function choose(value:string|number){store.selectObjective(value)}
async function objectiveNext(){try{await store.submitObjective()}catch(e){store.error=e instanceof Error?e.message:'提交失败'}}
async function send(){const content=draft.value.trim();if(!content||store.busy)return;draft.value='';try{const result=await store.sendContent(content,inputMode.value);speech.speak(result.turn.reply);inputMode.value='text'}catch{draft.value=content}}
async function skip(){try{await store.skipCurrent()}catch(e){store.error=e instanceof Error?e.message:'跳过失败'}}
async function finish(){try{await store.complete();await router.push('/app/profile-report')}catch(e){store.error=e instanceof Error?e.message:'生成报告失败'}}
function voice(){if(listening.value)speech.stopListening();else speech.startListening()}
function logout(){store.reset();auth.logout();router.replace('/login')}
</script>
<template><main class="app-page"><header class="app-header"><a class="wordmark" href="/app/exe"><span>策</span>Finance God</a><div class="header-actions"><span class="user-name">{{ auth.user?.display_name||auth.user?.email }}</span><button class="icon-button" aria-label="退出登录" title="退出登录" @click="logout"><LogOut :size="19"/></button></div></header>
  <div v-if="route.query.notice==='admin_required'" class="notice" role="status">此页面仅向管理员开放，已返回你的访谈。</div>
  <section v-if="phase==='loading'" class="center-state" aria-live="polite"><Sparkles :size="28"/><p>正在续上你的访谈…</p></section>
  <section v-else-if="phase==='restore_error'" class="center-state"><p class="form-error" role="alert">{{ store.error }}</p><button data-test="retry-restore" class="secondary-button" @click="restoreSession">重试</button></section>
  <section v-else-if="phase==='welcome'" class="mentor-stage"><div class="mentor-portrait"><img v-if="!mentorImageFailed" :src="mentorImageUrl" alt="原创传奇价值投资导师沈砚先生" @error="mentorImageFailed=true"><div v-else class="portrait-fallback" role="img" aria-label="投资导师形象暂未加载"><span>沈</span></div><span class="mentor-seal">价值一脉</span></div><div class="mentor-copy"><p class="chapter">序章 · 见自己</p><h1>我是沈砚先生。</h1><p class="lead">我们不猜明天涨跌。先谈清楚你的钱何时要用、能承受多少波动，以及什么会让你夜里睡不着。</p><p class="mentor-quote">“没有标准答案，也没有拒答的代价。”</p><button data-test="start-onboarding" class="primary-button inline-button" @click="started=true">开始问心十章<ArrowRight :size="19"/></button></div></section>
  <section v-else-if="phase==='objective'" class="question-stage"><div class="progress-row"><button class="back-button" :disabled="store.objectiveIndex===0" @click="store.previousObjective"><ArrowLeft :size="18"/>上一步</button><span>{{ store.objectiveIndex+1 }} / 10</span></div><div class="progress-track"><i :style="{width:`${progress*100}%`}"/></div><p class="chapter">{{ store.currentObjective.eyebrow }}</p><h1>{{ store.currentObjective.title }}</h1><div class="choice-grid"><button v-for="choice in store.currentObjective.choices" :key="String(choice.value)" data-test="objective-choice" class="choice-button" :class="{selected:store.objective[store.currentObjective.key]===choice.value}" @click="choose(choice.value)"><span>{{ choice.label }}</span><Check v-if="store.objective[store.currentObjective.key]===choice.value" :size="18"/></button></div><button v-if="store.objectiveIndex===9&&store.objectiveComplete" class="primary-button inline-button objective-submit" :disabled="store.busy" @click="objectiveNext">进入深聊<ArrowRight :size="19"/></button></section>
  <section v-else-if="phase==='conversation'" class="conversation-stage"><aside class="conversation-rail"><p class="chapter">问心对谈</p><h1>把真实想法说出来。</h1><span v-if="store.session?.provider_name==='mock'" class="mock-badge">模拟 AI</span><div class="round-orbit"><strong>{{ store.session?.round_count }}</strong><span>/ {{ store.session?.max_rounds }} 轮</span></div><div class="progress-track"><i :style="{width:`${progress*100}%`}"/></div><p>画像完整度 {{ Math.round(progress*100) }}%</p></aside><div class="conversation-main"><div ref="messageStream" class="message-stream" aria-live="polite"><article v-for="(message,index) in store.messages" :key="index" class="message" :class="message.role"><span class="speaker">{{ message.role==='assistant'?'沈砚':'你' }}</span><p>{{ message.content }}</p></article><article v-if="showQuestionCard" class="message assistant current-question"><span class="speaker">沈砚 · 当前问题</span><p>{{ currentQuestion }}</p></article><div v-if="store.busy" class="thinking"><Sparkles :size="17"/><span>{{ thinking[thinkingIndex] }}</span></div></div>
    <form class="composer" @submit.prevent="send"><textarea v-model="draft" rows="2" maxlength="4000" :disabled="store.busy" aria-label="回复沈砚" placeholder="跟沈砚聊聊你的想法…" @keydown.enter.exact.prevent="send"/><div class="composer-actions"><div><button type="button" class="icon-button" :class="{active:listening}" :aria-label="listening?'停止录音':'开始语音输入'" :title="listening?'停止录音':'开始语音输入'" @click="voice"><MicOff v-if="listening" :size="20"/><Mic v-else :size="20"/></button><button type="button" class="icon-button" :aria-label="speaking?'关闭语音播报':'开启语音播报'" :title="speaking?'关闭语音播报':'开启语音播报'" @click="speech.toggleSpeaking"><Volume2 v-if="speaking" :size="20"/><VolumeX v-else :size="20"/></button></div><button class="send-button" :disabled="!draft.trim()||store.busy" aria-label="发送"><Send :size="20"/></button></div></form><p v-if="speechError" class="inline-note" role="status">{{ speechError }}</p><button v-if="sensitive" class="text-button skip-link" @click="skip">可以跳过，不影响你的评价</button><p v-if="store.error" class="form-error" role="alert">{{ store.error }} <button class="text-button" @click="store.error=''">关闭</button></p></div></section>
  <section v-else-if="phase==='ready'" class="center-state ready-state"><Sparkles :size="30"/><p class="chapter">访谈已成卷</p><h1>你的投资画像已经清晰。</h1><p>接下来只呈现与你相配的方向，不给出收益承诺。</p><button class="primary-button inline-button" :disabled="store.busy" @click="finish">展开画像卷轴<ArrowRight :size="19"/></button></section>
</main></template>
