<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ArrowLeft, ArrowRight, Check, LogOut, Mic, MicOff, Phone, PhoneOff, Send, Sparkles } from 'lucide-vue-next'
import { useAuthStore } from '@/stores/auth';import { objectiveSteps, useOnboardingStore } from '@/stores/onboarding';import { useRealtimeVoice } from '@/composables/useRealtimeVoice'
import mentorImageUrl from '@/assets/images/investment-mentor.webp'
const store=useOnboardingStore(),auth=useAuthStore(),router=useRouter(),route=useRoute(),started=ref(false),draft=ref(''),inputMode=ref<'text'|'voice'>('text'),thinkingIndex=ref(0),mentorImageFailed=ref(false),finishing=ref(false),messageStream=ref<HTMLElement|null>(null);const voiceSession=reactive(useRealtimeVoice());const thinking=['正在梳理你的投资线索','正在权衡时间与风险','正在寻找下一位投资大师'];let timer:number|undefined
const phase=computed(()=>{if(!store.session)return store.error?'restore_error':'loading';if(store.session.step==='objective_profile')return started.value?'objective':'welcome';return store.session.step})
const progress=computed(()=>phase.value==='objective'?(store.objectiveIndex+1)/objectiveSteps.length:store.session?.completeness||0)
const sensitive=computed(()=>store.session?.current_dimension==='income_stability')
const currentQuestion=computed(()=>store.session?.current_question||'正在准备下一问…')
const showQuestionCard=computed(()=>{const q=(store.session?.current_question||'').trim();if(!q)return false;const lastAssistant=[...store.messages].reverse().find(m=>m.role==='assistant');return !lastAssistant||!lastAssistant.content.includes(q)})
async function restoreSession(){try{await store.restore();if(store.session?.objective_profile)started.value=true;if(localStorage.getItem('finance-god-profile-completed')==='true'){router.replace('/desk');return}}catch(e){store.error=e instanceof Error?e.message:'无法恢复会话'}}
onMounted(async()=>{await restoreSession();timer=window.setInterval(()=>thinkingIndex.value=(thinkingIndex.value+1)%thinking.length,1800)})
onBeforeUnmount(()=>clearInterval(timer));watch([()=>store.messages.length,currentQuestion],async()=>{await nextTick();if(messageStream.value)messageStream.value.scrollTop=messageStream.value.scrollHeight})
async function choose(value:string|number){store.selectObjective(value)}
async function objectiveNext(){try{await store.submitObjective()}catch(e){store.error=e instanceof Error?e.message:'提交失败'}}
async function send(){const content=draft.value.trim();if(!content||store.busy)return;draft.value='';try{await store.sendContent(content,inputMode.value);inputMode.value='text'}catch{draft.value=content}}
async function skip(){try{await store.skipCurrent()}catch(e){store.error=e instanceof Error?e.message:'跳过失败'}}
async function finish(){finishing.value=true;try{await store.complete();await router.push('/app/profile-report')}catch(e){finishing.value=false;store.error=e instanceof Error?e.message:'生成报告失败'}}
function appendVoiceTranscript(role:'user'|'assistant',content:string){store.messages.push({role,content});store.persistMessages()}
async function startVoice(){if(!store.session)return;await voiceSession.start({surface:'onboarding',sessionId:store.session.id,onFinalTranscript:appendVoiceTranscript})}
function logout(){store.reset();auth.logout();router.replace('/login')}
</script>
<template><main class="app-page"><header class="app-header"><a class="wordmark" href="/app/exe"><span>策</span>Finance God</a><div class="header-actions"><span class="user-name">{{ auth.user?.display_name||auth.user?.email }}</span><button class="icon-button" aria-label="退出登录" title="退出登录" @click="logout"><LogOut :size="19"/></button></div></header>
  <div v-if="route.query.notice==='admin_required'" class="notice" role="status">此页面仅向管理员开放，已返回你的访谈。</div>
  <transition name="phase" mode="out-in">
  <section v-if="phase==='loading'" class="center-state" aria-live="polite"><Sparkles :size="28"/><p>正在续上你的访谈…</p></section>
  <section v-else-if="phase==='restore_error'" class="center-state"><p class="form-error" role="alert">{{ store.error }}</p><button data-test="retry-restore" class="secondary-button" @click="restoreSession">重试</button></section>
  <section v-else-if="phase==='welcome'" class="mentor-stage"><div class="mentor-portrait"><img v-if="!mentorImageFailed" :src="mentorImageUrl" alt="原创传奇价值投资导师沈砚先生" @error="mentorImageFailed=true"><div v-else class="portrait-fallback" role="img" aria-label="投资导师形象暂未加载"><span>沈</span></div><span class="mentor-seal">价值一脉</span></div><div class="mentor-copy"><p class="chapter">序章 · 见自己</p><h1>我是沈砚先生。</h1><p class="lead">我们不猜明天涨跌。先谈清楚你的钱何时要用、能承受多少波动，以及什么会让你夜里睡不着。</p><p class="mentor-quote">“没有标准答案，也没有拒答的代价。”</p><button data-test="start-onboarding" class="primary-button inline-button" @click="started=true">开始问心十章<ArrowRight :size="19"/></button></div></section>
  <section v-else-if="phase==='objective'" class="question-stage"><div class="progress-row"><button class="back-button" :disabled="store.objectiveIndex===0" @click="store.previousObjective"><ArrowLeft :size="18"/>上一步</button><span>{{ store.objectiveIndex+1 }} / 10</span></div><div class="progress-track"><i :style="{width:`${progress*100}%`}"/></div><p class="chapter">{{ store.currentObjective.eyebrow }}</p><h1>{{ store.currentObjective.title }}</h1><div class="choice-grid"><button v-for="choice in store.currentObjective.choices" :key="String(choice.value)" data-test="objective-choice" class="choice-button" :class="{selected:store.objective[store.currentObjective.key]===choice.value}" @click="choose(choice.value)"><span>{{ choice.label }}</span><Check v-if="store.objective[store.currentObjective.key]===choice.value" :size="18"/></button></div><button v-if="store.objectiveIndex===9&&store.objectiveComplete" class="primary-button inline-button objective-submit" :disabled="store.busy" @click="objectiveNext">进入深聊<ArrowRight :size="19"/></button></section>
  <section v-else-if="phase==='conversation'" class="conversation-stage"><div class="conversation-status"><span v-if="store.session?.provider_name==='mock'" class="mock-badge">模拟 AI</span><span class="status-progress">画像完整度 {{ Math.round(progress*100) }}%</span></div><div class="conversation-main"><section v-if="voiceSession.active" class="live-call" aria-label="实时语音通话"><header><span class="live-indicator" aria-hidden="true"/><strong>{{ voiceSession.statusText }}</strong><small>StepAudio 2.5 Realtime</small></header><div class="live-transcripts" aria-live="polite"><article><span>你</span><p>{{ voiceSession.userTranscript||'正在等待你说话…' }}</p></article><article><span>沈砚</span><p>{{ voiceSession.assistantTranscript||'—' }}</p></article></div><div class="live-actions"><button type="button" class="secondary-button" @click="voiceSession.toggleMute"><Mic v-if="voiceSession.muted" :size="18"/><MicOff v-else :size="18"/>{{ voiceSession.muted?'取消静音':'静音' }}</button><button type="button" class="primary-button compact" @click="voiceSession.stop()"><PhoneOff :size="18"/>挂断</button></div></section><template v-else><div ref="messageStream" class="message-stream" aria-live="polite"><article v-for="(message,index) in store.messages" :key="index" class="message" :class="message.role"><span class="speaker">{{ message.role==='assistant'?'沈砚':'你' }}</span><p>{{ message.content }}</p></article><article v-if="showQuestionCard" class="message assistant current-question"><span class="speaker">沈砚 · 当前问题</span><p>{{ currentQuestion }}</p></article><div v-if="store.busy" class="thinking"><Sparkles :size="17"/><span>{{ thinking[thinkingIndex] }}</span></div></div>
    <form class="composer" @submit.prevent="send"><textarea v-model="draft" rows="2" maxlength="4000" :disabled="store.busy" aria-label="回复沈砚" placeholder="跟沈砚聊聊你的想法…" @keydown.enter.exact.prevent="send"/><div class="composer-actions"><button type="button" class="icon-button" aria-label="开始语音通话" title="开始语音通话" @click="startVoice"><Phone :size="20"/></button><button class="send-button" :disabled="!draft.trim()||store.busy" aria-label="发送"><Send :size="20"/></button></div></form></template><p v-if="voiceSession.error" class="inline-note" role="alert">{{ voiceSession.error }}</p><button v-if="sensitive" class="text-button skip-link" @click="skip">可以跳过，不影响你的评价</button><p v-if="store.error" class="form-error" role="alert">{{ store.error }} <button class="text-button" @click="store.error=''">关闭</button></p></div></section>
  <section v-else-if="phase==='ready'" class="center-state ready-state"><Sparkles :size="30"/><p class="chapter">访谈已成卷</p><h1>你的投资画像已经清晰。</h1><p>接下来只呈现与你相配的方向，不给出收益承诺。</p><button class="primary-button inline-button" :disabled="finishing" @click="finish">{{ finishing?'正在展开画像…':'展开画像卷轴' }}<ArrowRight v-if="!finishing" :size="19"/></button></section>
  </transition>
  <transition name="fade"><section v-if="finishing" class="finishing-overlay" aria-live="polite"><div class="unfurl" aria-hidden="true"/><p class="chapter">正在展开你的投资画像</p><p>沈砚正在为你成卷…</p></section></transition>
</main></template>
