<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';import { ArrowLeft, BookOpen, Check, ChevronRight, Compass, ShieldCheck } from 'lucide-vue-next';import { profileApi } from '@/api';import { directionScore, getSelectableDirections, localizeArchetype, localizeDimension, localizeProfileText } from '@/services/profile';import { saveAndEmitProfileCompleted, type HandoffStatus } from '@/services/workbench';import type { InvestmentDirection, ProfileWithRecommendations, Recommendation } from '@/types/api'
const data=ref<ProfileWithRecommendations|null>(null),loading=ref(true),saving=ref<string|null>(null),error=ref(''),showAll=ref(false),handoff=ref<HandoffStatus|null>(null);const sent=new Set<string>()
const directionNames:Record<InvestmentDirection,string>={cash_fixed_income:'守元诀',public_funds:'百川谱',equities:'青松录',alternatives:'观星篇',long_term_insurance:'长宁策'}
const directionKinds:Record<InvestmentDirection,string>={cash_fixed_income:'现金固收',public_funds:'公募基金',equities:'权益股票',alternatives:'另类配置',long_term_insurance:'长期储蓄保险'}
const visible=computed(()=>data.value?(showAll.value?data.value.recommendations:data.value.recommendations.slice(0,3)):[]);const selectable=computed(()=>data.value?getSelectableDirections(data.value):[])
onMounted(async()=>{try{data.value=await profileApi.latest()}catch(e){error.value=e instanceof Error?e.message:'报告加载失败'}finally{loading.value=false}})
async function choose(item:Recommendation){if(!data.value||saving.value||item.selected)return;saving.value=item.direction;error.value='';try{const payload={profileId:data.value.profile.id,sessionId:data.value.profile.session_id,selectedDirection:item.direction,archetypeCode:data.value.profile.archetype_code,riskLevel:data.value.profile.risk_level,completeness:data.value.profile.completeness};handoff.value=await saveAndEmitProfileCompleted(()=>profileApi.select(data.value!.profile.id,item.direction),window,import.meta.env.VITE_WORKBENCH_ORIGIN,payload,sent);data.value.recommendations.forEach(x=>x.selected=x.id===item.id)}catch(e){error.value=e instanceof Error?e.message:'保存方向失败'}finally{saving.value=null}}
</script>
<template><main class="report-page"><header class="app-header report-header"><RouterLink class="back-button" to="/app/exe"><ArrowLeft :size="18"/>返回访谈</RouterLink><span class="wordmark"><span>策</span>Finance God</span></header><section v-if="loading" class="center-state">正在展开画像…</section><section v-else-if="error&&!data" class="center-state"><p class="form-error">{{ error }}</p></section>
  <template v-else-if="data"><section class="report-intro"><div><p class="chapter">投资者画像 · 第 {{ data.profile.version }} 版</p><h1>{{ localizeArchetype(data.profile.archetype_title,data.profile.archetype_code) }}</h1><p class="report-lead">你重视边界，也愿意为长期目标留出耐心。画像不是标签，而是下一次决策前可重新翻阅的坐标。</p><div class="trait-row"><span v-for="trait in data.profile.report_summary.traits.slice(0,5)" :key="trait">{{ localizeProfileText(trait) }}</span></div></div><div class="profile-seal"><span>{{ Math.round(data.profile.completeness*100) }}</span><small>画像完整度</small></div></section>
    <section class="metric-band"><div><small>风险区间</small><strong>{{ {conservative:'稳健',moderate:'均衡',growth:'成长'}[data.profile.risk_level] }}</strong><span>阶段亏损参考 {{ data.profile.loss_tolerance_percent }}%</span></div><div><small>资金期限</small><strong>{{ {'under_1_year':'1 年以内','1_3_years':'1–3 年','3_5_years':'3–5 年','5_plus_years':'5 年以上'}[data.profile.objective_profile.fund_horizon] }}</strong><span>以实际用款变化为准</span></div><div><small>流动性</small><strong>{{ data.profile.dimension_scores.liquidity_resilience??'待确认' }}</strong><span>应急金 {{ data.profile.objective_profile.emergency_fund_months }} 个月</span></div><div><small>投资经验</small><strong>{{ {none:'初识',beginner:'入门',intermediate:'熟悉',advanced:'进阶'}[data.profile.objective_profile.investment_experience] }}</strong><span>不替代独立判断</span></div></section>
    <section class="report-details"><details open><summary><span><Compass :size="19"/>判断依据</span><ChevronRight :size="18"/></summary><ul><li v-for="reason in data.profile.report_summary.reasoning" :key="reason">{{ localizeProfileText(reason) }}</li></ul></details><details><summary><span><BookOpen :size="19"/>低置信度信息</span><ChevronRight :size="18"/></summary><p v-if="data.profile.report_summary.low_confidence.length">{{ data.profile.report_summary.low_confidence.map(localizeDimension).join('、') }} 尚需更多信息，未被当作确定事实。</p><p v-else>当前没有明显的低置信度维度。</p></details><details><summary><span><ShieldCheck :size="19"/>风险提醒</span><ChevronRight :size="18"/></summary><p>{{ localizeProfileText(data.profile.report_summary.risk_notice) }}</p></details></section>
    <section v-if="data.profile.education_only" class="education-band"><BookOpen :size="28"/><div><p class="chapter">金融教育模式</p><h2>先建立常识，再谈投资执行。</h2><p>未成年画像只提供储蓄、预算、风险与复利的基础教育方向，不支持选择可执行投资方向。</p></div></section>
    <section class="manual-section"><div class="section-heading"><div><p class="chapter">{{ data.profile.education_only?'启蒙篇':'与你相配的三本秘籍' }}</p><h2>{{ data.profile.education_only?'从稳健的金钱习惯开始':'方向比产品更重要' }}</h2></div><button v-if="!data.profile.education_only&&data.recommendations.length>3" class="secondary-button" @click="showAll=!showAll">{{ showAll?'只看前三':'查看另外两类' }}</button></div><div class="manual-grid"><article v-for="item in visible" :key="item.id" class="manual" :class="{featured:item.rank<=3,selected:item.selected}"><div class="manual-rank">{{ String(item.rank).padStart(2,'0') }}</div><p class="chapter">{{ directionKinds[item.direction] }}</p><h3>{{ directionNames[item.direction] }}</h3><p>{{ localizeProfileText(item.reason) }}</p><div class="score-line"><span>匹配度</span><i><b :style="{width:`${directionScore(item.score).percent}%`}"/></i><strong>{{ directionScore(item.score).label }}</strong></div><button v-if="selectable.some(x=>x.id===item.id)" data-test="select-direction" class="primary-button compact" :disabled="Boolean(saving)||item.selected" @click="choose(item)"><Check v-if="item.selected" :size="18"/><span>{{ item.selected?'已选定':'选择此方向' }}</span></button></article></div><p v-if="handoff==='sent'" class="success-note" role="status">方向已保存，正在交接外部工作台。</p><p v-else-if="handoff==='invalid_origin'" class="inline-note" role="status">方向已保存；工作台地址未配置，未发送浏览器消息。</p><p v-else-if="handoff==='no_target'" class="inline-note" role="status">方向已保存；当前未连接外部工作台。</p><p v-if="error" class="form-error" role="alert">{{ error }}</p></section>
  </template></main></template>
