<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';import { useRouter } from 'vue-router';import { ArrowLeft, BookOpen, Check, ChevronRight, Compass, ShieldCheck } from 'lucide-vue-next';import { profileApi } from '@/api';import { directionScore, getSelectableDirections, localizeArchetype, localizeDimension, localizeProfileText, masterPortraits, masterInitial } from '@/services/profile';import { saveAndEmitProfileCompleted } from '@/services/workbench';import type { InvestmentDirection, ProfileWithRecommendations, Recommendation } from '@/types/api'
const router=useRouter();const data=ref<ProfileWithRecommendations|null>(null),loading=ref(true),saving=ref<string|null>(null),error=ref(''),showAll=ref(false),portraitFailed=ref(false);const sent=new Set<string>()
const directionKinds:Record<InvestmentDirection,string>={cash_fixed_income:'现金与固收',public_funds:'公募基金',equities:'权益(股票)',alternatives:'另类配置',long_term_insurance:'长期储蓄保险'}
const visible=computed(()=>data.value?(showAll.value?data.value.recommendations:data.value.recommendations.slice(0,3)):[]);const selectable=computed(()=>data.value?getSelectableDirections(data.value):[])
onMounted(async()=>{try{data.value=await profileApi.latest()}catch(e){error.value=e instanceof Error?e.message:'报告加载失败'}finally{loading.value=false}})
async function choose(item:Recommendation){if(!data.value||saving.value||item.selected)return;saving.value=item.direction;error.value='';try{const payload={profileId:data.value.profile.id,sessionId:data.value.profile.session_id,selectedDirection:item.direction,archetypeCode:data.value.profile.archetype_code,riskLevel:data.value.profile.risk_level,completeness:data.value.profile.completeness};await saveAndEmitProfileCompleted(()=>profileApi.select(data.value!.profile.id,item.direction),window,import.meta.env.VITE_WORKBENCH_ORIGIN,payload,sent);await router.push('/desk')}catch(e){error.value=e instanceof Error?e.message:'保存方向失败'}finally{saving.value=null}}
</script>
<template><main class="report-page"><header class="app-header report-header"><RouterLink class="back-button" to="/app/exe"><ArrowLeft :size="18"/>返回访谈</RouterLink><span class="wordmark"><span>策</span>Finance God</span></header><section v-if="loading" class="center-state">正在展开画像…</section><section v-else-if="error&&!data" class="center-state"><p class="form-error">{{ error }}</p></section>
  <template v-else-if="data"><section class="master-hero"><div class="master-portrait"><img v-if="!portraitFailed" :src="masterPortraits[data.profile.style_code]" :alt="data.profile.master_name" @error="portraitFailed=true"><div v-else class="portrait-fallback" role="img" :aria-label="data.profile.master_name"><span>{{ masterInitial(data.profile.master_name) }}</span></div></div><div class="master-copy"><p class="chapter">投资风格 · {{ data.profile.style_logic }}</p><h1>{{ data.profile.style_name }}</h1><p class="report-lead">{{ data.profile.style_summary }}</p><p class="master-line">你的投资风格最接近 <strong>{{ data.profile.master_name }}</strong> · {{ data.profile.master_name_en }}</p><p class="match-reason">{{ data.profile.master_match_reason }}</p><p class="hero-note">投资风格标杆 · 理念相近，非收益承诺。</p><div class="trait-row"><span v-for="trait in data.profile.report_summary.traits.slice(0,5)" :key="trait">{{ localizeProfileText(trait) }}</span></div></div></section>
    <section class="metric-band"><div><small>风险分类</small><strong>{{ localizeArchetype(data.profile.archetype_title,data.profile.archetype_code) }}</strong><span>完整度 {{ Math.round(data.profile.completeness*100) }}%</span></div><div><small>风险区间</small><strong>{{ {conservative:'稳健',moderate:'均衡',growth:'成长'}[data.profile.risk_level] }}</strong><span>阶段亏损参考 {{ data.profile.loss_tolerance_percent }}%</span></div><div><small>资金期限</small><strong>{{ {'under_1_year':'1 年以内','1_3_years':'1–3 年','3_5_years':'3–5 年','5_plus_years':'5 年以上'}[data.profile.objective_profile.fund_horizon] }}</strong><span>以实际用款变化为准</span></div><div><small>流动性</small><strong>{{ data.profile.dimension_scores.liquidity_resilience??'待确认' }}</strong><span>应急金 {{ data.profile.objective_profile.emergency_fund_months }} 个月</span></div><div><small>投资经验</small><strong>{{ {none:'初识',beginner:'入门',intermediate:'熟悉',advanced:'进阶'}[data.profile.objective_profile.investment_experience] }}</strong><span>不替代独立判断</span></div></section>
    <section class="report-details"><details open><summary><span><Compass :size="19"/>判断依据</span><ChevronRight :size="18"/></summary><ul><li v-for="reason in data.profile.report_summary.reasoning" :key="reason">{{ localizeProfileText(reason) }}</li></ul></details><details><summary><span><BookOpen :size="19"/>低置信度信息</span><ChevronRight :size="18"/></summary><p v-if="data.profile.report_summary.low_confidence.length">{{ data.profile.report_summary.low_confidence.map(localizeDimension).join('、') }} 尚需更多信息，未被当作确定事实。</p><p v-else>当前没有明显的低置信度维度。</p></details><details><summary><span><ShieldCheck :size="19"/>风险提醒</span><ChevronRight :size="18"/></summary><p>{{ localizeProfileText(data.profile.report_summary.risk_notice) }}</p></details></section>
    <section v-if="data.profile.education_only" class="education-band"><BookOpen :size="28"/><div><p class="chapter">金融教育模式</p><h2>先建立常识，再谈投资执行。</h2><p>未成年画像只提供储蓄、预算、风险与复利的基础教育方向，不支持选择可执行投资方向。</p></div></section>
    <section class="manual-section"><div class="section-heading"><div><p class="chapter">{{ data.profile.education_only?'金融教育方向':'推荐配置方向' }}</p><h2>{{ data.profile.education_only?'从稳健的金钱习惯开始':'按匹配度排序，方向仅供参考' }}</h2></div><button v-if="!data.profile.education_only&&data.recommendations.length>3" class="secondary-button" @click="showAll=!showAll">{{ showAll?'只看前三':'查看另外两类' }}</button></div><div class="manual-grid"><article v-for="item in visible" :key="item.id" class="manual" :class="{featured:item.rank<=3,selected:item.selected}"><div class="manual-rank">{{ String(item.rank).padStart(2,'0') }}</div><h3>{{ directionKinds[item.direction] }}</h3><p>{{ localizeProfileText(item.reason) }}</p><div class="score-line"><span>匹配度</span><i><b :style="{width:`${directionScore(item.score).percent}%`}"/></i><strong>{{ directionScore(item.score).label }}</strong></div><button v-if="selectable.some(x=>x.id===item.id)" data-test="select-direction" class="primary-button compact" :disabled="Boolean(saving)||item.selected" @click="choose(item)"><Check v-if="item.selected" :size="18"/><span>{{ item.selected?'已选定':'选择此方向' }}</span></button></article></div><p v-if="error" class="form-error" role="alert">{{ error }}</p></section>
  </template></main></template>
